models:
  default: "gpt-4"
  available_models:
    - gpt-4
    - gpt-3.5-turbo
    - claude-instant
    - mistral-7b
    - llama-2-13b
api_keys:
  openai: "sk-test-1234"  
  anthropic: "sk-test-5678"
pricing:
  token_limit: 5000
  cost_per_token: 0.002
storage:
  usage_percentage: 30
