models:
  gpt-4:
    name: GPT-4
    cost_per_1k_tokens: 0.03
  gpt-3.5-turbo:
    name: GPT-3.5
    cost_per_1k_tokens: 0.002
  claude-2:
    name: Claude 2
    cost_per_1k_tokens: 0.025
  llama-2:
    name: Llama 2
    cost_per_1k_tokens: 0.001
  mistral-7b:
    name: Mistral 7B
    cost_per_1k_tokens: 0.0005
default_model: gpt-3.5-turbo
user_name: User
theme: light